var hierarchy =
[
    [ "Application", "classApplication.html", null ],
    [ "Camera2D", "classCamera2D.html", null ],
    [ "CameraController", "classCameraController.html", null ],
    [ "ECSScene", "classECSScene.html", null ],
    [ "Components::Enemy", "structComponents_1_1Enemy.html", null ],
    [ "Demo2DFixedScene::EnemyDefinition", "structDemo2DFixedScene_1_1EnemyDefinition.html", null ],
    [ "LevelSystem::EnemyDefinition", "structLevelSystem_1_1EnemyDefinition.html", null ],
    [ "EnemySystem", "classEnemySystem.html", null ],
    [ "Engine", "classEngine.html", null ],
    [ "Event", "classEvent.html", [
      [ "EnemyDiedEvent", "classEnemyDiedEvent.html", null ],
      [ "KeyEvent", "classKeyEvent.html", null ],
      [ "MouseButtonEvent", "classMouseButtonEvent.html", null ],
      [ "MouseMotionEvent", "classMouseMotionEvent.html", null ],
      [ "MouseWheelEvent", "classMouseWheelEvent.html", null ],
      [ "PlayerDiedEvent", "classPlayerDiedEvent.html", null ],
      [ "PlayerJumpedEvent", "classPlayerJumpedEvent.html", null ],
      [ "PlayerLandedEvent", "classPlayerLandedEvent.html", null ],
      [ "WindowCloseEvent", "classWindowCloseEvent.html", null ],
      [ "WindowResizeEvent", "classWindowResizeEvent.html", null ]
    ] ],
    [ "EventBus", "classEventBus.html", null ],
    [ "EventDispatcher", "classEventDispatcher.html", null ],
    [ "Font", "classFont.html", null ],
    [ "FpsCounter", "classFpsCounter.html", null ],
    [ "GameObject", "classGameObject.html", null ],
    [ "GamepadManager", "classGamepadManager.html", null ],
    [ "GameWorld", "classGameWorld.html", null ],
    [ "GraphicsContext", "classGraphicsContext.html", null ],
    [ "HUD", "classHUD.html", null ],
    [ "IndexBuffer", "classIndexBuffer.html", null ],
    [ "Input", "classInput.html", null ],
    [ "LevelDefinition", "structLevelDefinition.html", null ],
    [ "LevelRegistry", "classLevelRegistry.html", null ],
    [ "LevelSystem", "classLevelSystem.html", null ],
    [ "Log", "classLog.html", null ],
    [ "Matrix4", "classMatrix4.html", null ],
    [ "MenuScene::MenuOption", "structMenuScene_1_1MenuOption.html", null ],
    [ "LevelSelectorScene::Option", "structLevelSelectorScene_1_1Option.html", null ],
    [ "Components::Patrol", "structComponents_1_1Patrol.html", null ],
    [ "Components::PhysicsBody", "structComponents_1_1PhysicsBody.html", null ],
    [ "PlayerController", "classPlayerController.html", null ],
    [ "Renderer", "classRenderer.html", null ],
    [ "RenderSystem", "classRenderSystem.html", null ],
    [ "ResourceManager", "classResourceManager.html", null ],
    [ "Scene", "classScene.html", [
      [ "BaseLevelScene", "classBaseLevelScene.html", null ],
      [ "Demo2DFixedScene", "classDemo2DFixedScene.html", null ],
      [ "Demo2DScene", "classDemo2DScene.html", null ],
      [ "LevelSelectorScene", "classLevelSelectorScene.html", null ],
      [ "MenuScene", "classMenuScene.html", null ]
    ] ],
    [ "SceneManager", "classSceneManager.html", null ],
    [ "SDLEventTranslator", "classSDLEventTranslator.html", null ],
    [ "SDLWindow", "classSDLWindow.html", null ],
    [ "Shader", "classShader.html", null ],
    [ "SoundEffect", "classSoundEffect.html", null ],
    [ "SoundManager", "classSoundManager.html", null ],
    [ "Components::SpriteRenderer", "structComponents_1_1SpriteRenderer.html", null ],
    [ "Texture2D", "classTexture2D.html", null ],
    [ "Components::TileScale", "structComponents_1_1TileScale.html", null ],
    [ "Time", "classTime.html", null ],
    [ "Components::Transform", "structComponents_1_1Transform.html", null ],
    [ "Transform", "structTransform.html", null ],
    [ "Vector2D", "structVector2D.html", null ],
    [ "Vector3D", "structVector3D.html", null ],
    [ "VertexArray", "classVertexArray.html", null ],
    [ "VertexBuffer", "classVertexBuffer.html", null ]
];